variables:

# Workspace settings
  ml_workspace_connection: azureml_connection
  ml_workspace_name: ai-factory
  ml_workspace_rg: ai-factory

# Factory settings
  factory_github_connection: github_connection
  factory_template_repo: ai-factory-azure/templates-mlops
  factory_project_repo: ai-factory-azure/project-template-tabular-batch-code

# Training pipeline settings

  # Training AzureML Environment name
  training_environment_name: credit-training

  # Training AzureML Environment conda yaml
  training_environment_conda_yaml: controller/environments/train.yml

  # Name for the training pipeline
  training_pipeline_name: credit-training

  # Compute target for pipeline
  training_pipeline_target: cpu-cluster

  # Command to run for training, use azureml:dataset_name:version to reference a dataset
  training_command: 'train.py --data_path azureml:uci-credit:1'

  # Name under which the model will be registered
  model_name: credit-ci

# Batch pipeline settings

  # Batch AzureML Environment name
  batch_environment_name: credit-batch

  # Batch AzureML Environment conda yaml
  batch_environment_conda_yaml: controller/environments/batch.yml

  # Name for the batch scoring pipeline
  batch_pipeline_name: credit-batch-scoring

  # Compute target for pipeline
  batch_pipeline_target: cpu-cluster

  # Input batch dataset
  batch_input_dataset_name: credit-batch-input

  # Output dataset with results
  batch_output_dataset_name: credit-batch-output
  batch_output_path_on_datastore: credit-batch-scoring-results/{run-id}
  batch_output_filename: results.csv

  # Parallelization settings
  batch_mini_batch_size: 8
  batch_error_threshold: 1
  batch_process_count_per_node: 1
  batch_node_count: 1